version: 2.1

orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm test
          working_directory: ./server
  docker-publish:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            echo "$DOCKERHUB_PASSWORD" | sudo docker login --username $DOCKERHUB_USER --password-stdin
            sudo docker build ./server -t zarczynsky/node-react-db
            sudo docker push zarczynsky/node-react-db
workflows:
    build-and-test:
      jobs:
        - build-and-test:
              filters:
                branches:
                  only: master
        - docker-mk:
              requires:
                - build-and-test
              filters:
                branches:
                  only: master
